### ISSUE TITLE
Does not compile on gcc 4.6, potential issue with how open is called

### ISSUE THREAD

**Issue by vilhelmp** [kenyoung/SMARechunker#1]
I don't know what gcc version you are running this on, but compiling it on gcc 4.6 does not work because of how "open" is called. For me it throws the error that it is missing the last argument. Thus if you change all instances of `open(fileName, O_WRONLY|O_CREAT);` to `open(fileName, O_WRONLY|O_CREAT,0xFFFF);` in SMARechunker.c it should work on gcc 4.6 as well.

**Comment by kenyoung** [comment]
Thanks for catching this!   Sorry I didn't see the bug report quickly.   I was unaware that the access permissions fild was manditory with O_CREAT.   I've modified the code, but I'm using the symbolic  S_IRUSR|S_IWUSR|S_IRGRP rather than 0xFFFF.

**Comment by vilhelmp** [comment]
Ah, OK great. I guess it is just version dependent.
