### ISSUE TITLE
Does not compile on gcc 4.6, -lm flag in wrong place

### ISSUE THREAD

**Issue by vilhelmp** [kenyoung/SMARechunker#2]
In the Makefile, the -lm flag is given in the beginning. Compiling with Intel works, but not with gcc 4.6. Putting the -lm flag last fixes this. Thus the Makefile should have:

`gcc -O3 -funroll-loops -funsafe-loop-optimizations -Wall -o SMARechunker SMARechunker.c -lm`

to be more generally applicable.

**Comment by kenyoung** [comment]
Thanks for catching this.   I've made the change you proposed.   Are you actually using SMARechunker on a non x86 machine?

**Comment by vilhelmp** [comment]
It's a x86_64 machine. Using the Intel compiler it actually works even if the -lm is at the beginning, but it prints a more informative warning.
